### ISSUE TITLE
Doco fixup 2024-01

### ISSUE THREAD

**Issue by apjanke** [apjanke/octave-tablicious#110]
Some problems with the doco.

## TODO

* [ ] Get generated doco building again, with contemporary toolchain.
* [ ] Publish updated doco to GH Pages.
* [ ] Consider switching to using the [pkg-octave-doc package](https://github.com/gnu-octave/pkg-octave-doc) to generate doco.
* [ ] Consider changing `{Function}` to `{Tablicious}` in `@deftypefn`s like Statistics does.

## References

* [Suggestions from pr0m1th3as (Statistics) in other issue comment](https://github.com/apjanke/octave-tablicious/issues/108#issuecomment-1914516839)

**Comment by apjanke** [comment]
Moved milestone from 0.4.0 to 0.5.0 because I want to do 0.4.0 soon for Statistics compatibility and some basic fixes, and the relevant items in this ticket for that are fixed now I think. Further items like `string` doco improvement and switching to a different doc-building tool can wait until the next release.
