### ISSUE TITLE
Change release dates in doco to be UTC (and other dates too)

### ISSUE THREAD

**Issue by apjanke** [apjanke/octave-tablicious#126]
The dates in my documentation in some places use my local calendar date, which is US Eastern Time. Would be probably be better to use UTC, for global applicability, and bc that seems to be what the Octave package index uses (like in https://github.com/gnu-octave/packages/pull/401). Let's change to UTC dates.

## TODO

* [x] Retroactively change the release dates in `CHANGES.txt` and other release histories. (Just 0.3.7 I think.)
* [X] Change the docgen tools to use UTC dates.
  * Not needed, I think: docgen uses mtimes of source files, which are POSIX times in UTC; and that date only shows up in the PDF format, and only precise to the month.
  * Though maybe it should be using the nominal release date from DESCRIPTION instead of any file mtimes anyway
* [X] Anything else? Are there timestamps in any of our test output?
  * I don't see any.

Too late to change the dates in old generated doco; I thihk released archives should stay immutable.
