### ISSUE TITLE
Some BISTs failing, maybe due to floating-point precision issues

### ISSUE THREAD

**Issue by apjanke** [apjanke/octave-tablicious#84]
Kai reports some BISTs are failing now.

## TODO

* [x] Remember or figure out how to run all the BISTs in the package.
* [x] Look at other OF packages to see what they do for test suites. Especially Statistics and IO.
* [x] Find and fix the failing BISTs. 

## References

* https://wiki.octave.org/Tests
* https://github.com/apjanke/octave-tablicious/issues/30

**Comment by apjanke** [comment]
I did a little reading, and found my `dev-tools/runtests.sh`, which calls Octaves `runtests()` function, pointed at the package's `inst` dir. But in Octave 8.x, there's no `runtests()` any more. I guess it got replaced with something else in the last couple major versions. Need to read and figure that out.

**Comment by apjanke** [comment]
Hmm. I looked through `doc test` and [this Tests page on the Octave wiki](https://wiki.octave.org/Tests), and it doesn't look like there's currently a tool for running all the BISTs in a directory or package? Just `test` for running a single test on a function, and `__run_test_suite__` for running all the BISTs in Octave itself.

This may be a fair amount of work, since I may have to set up my own test suit runner? Have a look at other Octave Forge packages and see what they do here.

Moving the milestone for this to 0.5.0.

**Comment by apjanke** [comment]
BISTs are passing now. (Though I don't know which were failing in the first place at the time this bug was reported.)

Was a bug in NaN handling in time zone conversion for datetime, fixed in https://github.com/apjanke/octave-tablicious/commit/76ffcecc449d1df13e45fae271f9384d741cce4f.

Also was a bad reference value in one of the `string` tests with respect to missing-val conversion. Fixed that by changing the test (to expect `string(NaN)` to convert to missing instead of `"NaN"`).

Closing as Fixed.
